# Submission

In [6]:
import math
import numpy as np

In [ ]:
def mult_table(N): 
    """ function creates the multiplication table of inputed number """
    
    for i in range (12):
        print (N, "x", i+1, "=", N*(i+1))
        
N = int(input("What number do you want to get it's multiplication table? \n"))
print ("The multiplication table for {} is". format(N))

mult_table(N)

In [ ]:
def isPrime(n):
    """ function checks if number is a prime number """
    
    for i in range (2, n):
        if n % i == 0:
            return False
    return True

def listTwinPrime(N):
    """ function to twin prime numbers   """

    for a in range (2, N):
        b = a + 2
        if isPrime(a) and isPrime(b):
            print ("{} and {}" .format(a, b))
            
print ("List of Twin Primes:")
            
listTwinPrime (1000)

In [ ]:
prime_list = []

def primeFactors(x):
    """ function lists the prime factors of a given number """

    while x % 2 == 0:
        prime_list.append(2)
        x = x/2

    for i in range(3, int(math.sqrt(x))+1, 2):
        while x % i == 0:
            prime_list.append(i)
            x = x/i

    if x > 2:
        x = int(x)
        prime_list.append(x)
    return prime_list

primeFactors(56)

In [ ]:
full_list = [3, 5, 88, 23, 9, 123, 60, 11, 92, 16, 44, 65, 111, 92, 81, 14, 45, 33, 4, 52, 66, 76, 123, 243, 442]

def check_odd(num):
    if num % 2 != 0:
        return True
    return False

odd_num_check = filter(check_odd, full_list)
odd_num_list = list(odd_num_check)

print (odd_num_list)


In [3]:
def prodDigits(x):
    """ function returns the product of digits of given number """
    n = x
    prod = 1
    while n > 0:
        digit = n % 10
        prod *= digit
        n //= 10
    return prod

x = int(input("Enter any number : "))
y = prodDigits (x)
print("The product of the digits of {} is: {}".format(x, y))

Enter any number : 54
The product of the digits of 54 is: 20


In [7]:
list = [12.23, 13.32, 100, 36.32]

print("Original List:",list)
a = np.array(list)
print("One-dimensional NumPy array: ",a)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


In [8]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
x = np.zeros(10)
print(x)

x[6] = 11 #update the sixth value to 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
